### ISSUE TITLE
Extension to DeepSeek

### ISSUE THREAD

**Issue by fillassuncao** [epfl-dlab/transformers-CFG#72]
First of all, thank you for the amazing work: `transformers-cfg` really makes it easy to build ebnf-based constrained decoding 🚀 

While trying to do so with DeepSeek-Coder (e.g. [of the 1.3b model](https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-base)), I have realised that even though it is LLaMa-based, `transformers-cfg` does not support it. 

After deep-diving into the code of the package I found the root: in the `ByteProxyMapping`, the `decode_proxytoken2bytes` has ad hoc patches for BPE. The problem is that the space before tokens, in DeepSeek, is not encoded using `_`, but using `Ġ` instead. In addition, there are other special cases, e.g., `\t` is encoded as `ĉ`, and `\n` as `Ċ`.

To patch it, I am overriding the `decode_proxytoken2bytes` with the bellow:

```
def decode_proxytoken2bytes(self: ByteProxyMapping, proxy_token: str) -> bytes:
    """Hammered function to replace the deepseek non ascii tokens."""
    if proxy_token.startswith("<0x"):
        hex_value: str = proxy_token[3:-1]
        return bytes.fromhex(hex_value)
    else:
        # ad hoc fix for BPE
        if "Ċ" in proxy_token:
            proxy_token = proxy_token.replace("Ċ", "\n")
        if "ĉ" in proxy_token:
            proxy_token = proxy_token.replace("ĉ", "\t")
        if proxy_token.startswith("Ġ"):
            proxy_token = proxy_token.replace("Ġ", " ")
        return proxy_token.encode("utf-8")
```

But certainly, a cleaner and more generalisable approach, that is tokenizer independent exists 🤔

**Comment by Saibo-creator** [comment]
Hello @fillassuncao ,
      I'm glad to hear that transformers-cfg has been helpful for your work :)

      Regarding DeepSeek-Coder, your observation is right. Even though it is instantiated as a Llama_tokenizer, but the actual token encodings is rather using the same method as GPT-2. 

If you print out the vocab of GPT2, you will see that they also have `\t` is encoded as `ĉ`, and `\n` as `Ċ` etc. 

I just made a fix and now the main branch should support it. (It passed all my tests)

**Comment by fillassuncao** [comment]
I have looked into the PR and overall the solution seems to work. For our specific use-cases there is only a blocker, we are actually loading fine-tuned versions of the models, with added special tokens, and therefore we also need to load the tokenizer. With that in mind, the `name_or_path` will not start by `deepseek-ai/deepseek-coder`.

What if we add a new classmethod that enables specifying the tokenizer middle mapping that should be used for the tokenizer? 🤔 This would likely imply changes in other places too.

Additionally, is there any reason why there are no releases of the package since march?

**Comment by Saibo-creator** [comment]
Hello @fillassuncao,

I see. Indeed, relying on the `name_or_path` isn't a general solution.

Maybe we can auto-infer the tokenizer middle mapping by examining the vocab. I have a draft here (not tested): [Draft Code](https://github.com/epfl-dlab/transformers-CFG/blob/main/transformers_cfg/tokenization/middle/TokenizerMiddleMapping.py#L55).

I can look into this. If it doesn't work, we could ask users to specify the tokenizer middle mapping, but I'm hesitant because exposing this detail might be too complicated. Alternatively, we could ask users to specify the base model, but this can also be messy, especially with third-party models where it's hard to know which base model they used.

So, I hope the auto-infer approach will work, and I think it probably will.

Is this feature blocking you? I may have time to add this feature this weekend, but I can't guarantee it. For now, you could replace `deepseek-ai/deepseek-coder` with your model name as a temporary workaround 😁

**Comment by Saibo-creator** [comment]
@fillassuncao Regarding your question about the lack of releases since March:

My reasoning is that since the project is **lightweight** and **purely Python**, frequent releases don’t seem necessary. In contrast, if it were a C++ project requiring compilation, regular releases would make more sense to ease installation and pinpoint specific code versions. While I acknowledge the benefit of versioning, my current plan is to maintain the main branch as the reference and occasionally push updates to PyPi.

Is there another reason you think we should be doing more frequent releases? If it makes sense, I'm open to packaging releases more regularly. Please let me know 😉

**Comment by fillassuncao** [comment]
Hello @Saibo-creator,

Sorry for the late reply!

Regarding the first question, the issue is not blocking us currently. We have it patched on our end, directly in the needed place (in a way, it is a hotfix, that just enables running with deepseek, but for now that is fine!). I have looked into the draft PR and it really looks like a possible solution, thanks for sharing!

Focusing on the releases, we manage the dependencies using poetry. We can always install from the `main` branch (or a specific commit), but this way we need to be very careful when updating the package version to make sure there were no major (breaking) changes committed to main. On the other hand, we were initially just installing the released version (which is considerably outdated), and only then realised the date of the last commits to main and the differences in the code.

**Comment by Saibo-creator** [comment]
Thanks for the explanation, that makes sense. The fact that releases are very outdated could indeed create troubles to users. I will keep them updated :)

**Comment by Saibo-creator** [comment]
@fillassuncao  I’ve just set up the automatic update workflow for PyPI. Thanks again for your feedback!  PR #78
